#Properties config
property_files:
  - properties

#Dependency Injector
dependency_injector:
  module_name: framework.plugins.dependency_injector
  class_name: KartaDependencyInjector

# Plugins for Karta
plugins:
  Kriya:
    module_name: framework.plugins.kriya
    class_name: Kriya
    init:
      kwargs:
        step_def_package: step_definitions
        feature_directory: features

  Gherkin:
    module_name: framework.plugins.gherkin
    class_name: GherkinPlugin
    init:
      kwargs:
        feature_directory: features

  LoggingTestLifecycleHook:
    module_name: framework.plugins.listeners
    class_name: LoggingTestLifecycleHook

  JSONEventDumper:
    module_name: framework.plugins.listeners
    class_name: DumpToJSONEventListener
    init:
      kwargs:
        json_file_name: results/events.json

#Step Runners plugin name
step_runners:
  - Kriya

#Feature Parsers plugin names mapped to file extensions
parser_map:
  .yml: Kriya
  .yaml: Kriya
  .feature: Gherkin

#Test Catalog Manager plugin name
test_catalog_manager: Kriya

test_lifecycle_hooks:
  - LoggingTestLifecycleHook

test_event_listeners:
  - JSONEventDumper